# SonarQube project configuration
sonar.projectKey=ecommerce-app
sonar.projectName=Shop-App
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.language=js

# Exclude folders
sonar.exclusions=**/node_modules/**, **/.next/**, **/out/**, **/build/**, **/dist/**, **/*.test.js, **/*.spec.js

# JavaScript/TypeScript
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
